name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: configure
    #   run: ./configure

    - name: Install lcov
      run: sudo apt install lcov
    # Install dependencies (Boost, cpplint, lcov, genhtml)
    - name: Install Boost, genhtml, asio
      run: |
        sudo apt-get update
        sudo apt install libasio-dev
    - name: Install cpplint
      run: pip3 install cpplint

    # Fetch Crow and Asio libraries using CMake's FetchContent (handled in CMakeLists.txt)
    - name: Build with CMake
      run: |
           cd IndividualMiniprojectC++
           cmake .
           make
    - name: Run Unit Tests
      run: cd IndividualMiniprojectC++
           make test
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
